import { z } from "zod";

// Schéma de formulaire
export const formSchema = z.object({
  // Informations générales
  city: z.string().min(1, "La ville est requise"),
  country: z.string().min(1, "Le pays est requis"),
  region: z.string().optional(),
  diagnostic_date: z.string().optional(),
  population_total: z.string().optional(),
  population_density: z.string().optional(),
  area_km2: z.string().optional(),
  
  // SOCIETY
  primary_school_enrollment: z.string().optional(),
  secondary_school_enrollment: z.string().optional(),
  tertiary_enrollment: z.string().optional(),
  adult_literacy_rate: z.string().optional(),
  youth_literacy_rate: z.string().optional(),
  gender_parity_index: z.string().optional(),
  crime_rate: z.string().optional(),
  safety_perception: z.string().optional(),
  healthcare_access: z.string().optional(),
  doctors_per_10000: z.string().optional(),
  hospital_beds_per_10000: z.string().optional(),
  life_expectancy: z.string().optional(),
  infant_mortality: z.string().optional(),
  maternal_mortality: z.string().optional(),
  vaccination_rate: z.string().optional(),
  malnutrition_rate: z.string().optional(),
  urban_poverty_rate: z.string().optional(),
  social_inclusion_index: z.string().optional(),
  community_participation_rate: z.string().optional(),
  social_protection_coverage: z.string().optional(),
  
  // HABITAT
  water_access: z.string().optional(),
  water_quality: z.string().optional(),
  electricity_access: z.string().optional(),
  clean_cooking_fuels: z.string().optional(),
  housing_overcrowding: z.string().optional(),
  informal_housing_percentage: z.string().optional(),
  housing_cost_per_m2: z.string().optional(),
  home_ownership_rate: z.string().optional(),
  sanitation_access: z.string().optional(),
  wastewater_treatment: z.string().optional(),
  homelessness_rate: z.string().optional(),
  housing_satisfaction_rate: z.string().optional(),
  housing_affordability_index: z.string().optional(),
  slum_population_percentage: z.string().optional(),
  
  // SPATIAL
  urban_density: z.string().optional(),
  green_space_per_capita: z.string().optional(),
  public_transport_access: z.string().optional(),
  home_work_distance: z.string().optional(),
  urbanization_rate: z.string().optional(),
  planned_vs_informal_ratio: z.string().optional(),
  functional_mix_index: z.string().optional(),
  sports_cultural_access: z.string().optional(),
  walkability_score: z.string().optional(),
  bike_lane_density: z.string().optional(),
  public_space_access: z.string().optional(),
  
  // INFRASTRUCTURE
  road_quality_percentage: z.string().optional(),
  road_length_per_capita: z.string().optional(),
  internet_access: z.string().optional(),
  broadband_speed: z.string().optional(),
  mobile_penetration: z.string().optional(),
  water_reliability: z.string().optional(),
  electricity_reliability: z.string().optional(),
  public_transport_capacity: z.string().optional(),
  motorization_rate: z.string().optional(),
  accessibility_pmr: z.string().optional(),
  drainage_coverage: z.string().optional(),
  street_lighting_coverage: z.string().optional(),
  digital_services_index: z.string().optional(),
  
  // ENVIRONMENT
  air_quality_pm25: z.string().optional(),
  air_quality_pm10: z.string().optional(),
  waste_collection_rate: z.string().optional(),
  waste_recycling_rate: z.string().optional(),
  waste_to_energy_rate: z.string().optional(),
  sanitation_coverage: z.string().optional(),
  climate_vulnerability_index: z.string().optional(),
  heatwave_days_per_year: z.string().optional(),
  flood_risk_areas: z.string().optional(),
  renewable_energy_share: z.string().optional(),
  urban_deforestation_rate: z.string().optional(),
  climate_adaptation_plan: z.string().optional(),
  biodiversity_index: z.string().optional(),
  carbon_footprint_per_capita: z.string().optional(),
  
  // GOVERNANCE
  corruption_index: z.string().optional(),
  voter_turnout: z.string().optional(),
  women_in_council: z.string().optional(),
  youth_in_council: z.string().optional(),
  elected_council_exists: z.string().optional(),
  public_service_satisfaction: z.string().optional(),
  open_data_access: z.string().optional(),
  political_stability_index: z.string().optional(),
  citizen_initiatives_supported: z.string().optional(),
  budget_transparency: z.string().optional(),
  participatory_budgeting: z.string().optional(),
  digital_governance_index: z.string().optional(),
  
  // ECONOMY
  unemployment_rate: z.string().optional(),
  youth_unemployment: z.string().optional(),
  female_labor_participation: z.string().optional(),
  formal_employment_rate: z.string().optional(),
  gdp_per_capita: z.string().optional(),
  gdp_growth_rate: z.string().optional(),
  fdi_attractiveness: z.string().optional(),
  business_creation_rate: z.string().optional(),
  income_per_capita: z.string().optional(),
  microcredit_access_rate: z.string().optional(),
  cost_of_living_index: z.string().optional(),
  monetary_poverty_rate: z.string().optional(),
  green_digital_economy_share: z.string().optional(),
  informal_economy_share: z.string().optional(),
  tourism_revenue: z.string().optional(),
  
  // Objectifs
  diagnostic_type: z.string().optional(),
  diagnostic_objective: z.string().optional(),
  additional_comments: z.string().optional(),
});